// src/components/advanced-search/box-types/BidiClass.svelte
<script lang="ts">
	import { BidiClassMap } from '$utils/unicode';

	export let data: string;

	import Dropdown from '../Dropdown.svelte';

	const displayToBidiMap = new Map(
		[...BidiClassMap.entries()].map(([className, displayName]) => {
			return [`${className} (${displayName})`, className];
		})
	);
	const names = [...displayToBidiMap.keys()];

	let displayName: string = names[0];

	$: {
		data = displayToBidiMap.get(displayName)!;
	}
</script>

<Dropdown options={names} hue={35} bind:value={displayName} />

// src/components/advanced-search/box-types/BidiClass.tsx
import { createSignal, createEffect } from "solid-js";
import { BidiClassMap } from "$utils/unicode";
import { Dropdown } from "../Dropdown";

interface BidiClassProps {
  data?: string;
  onDataChange?: (data: string) => void;
}

const displayToBidiMap = new Map(
  [...BidiClassMap.entries()].map(([className, displayName]) => {
    return [`${className} (${displayName})`, className];
  }),
);
const names = [...displayToBidiMap.keys()];

export function BidiClass(props: BidiClassProps) {
  const [displayName, setDisplayName] = createSignal<string>(names[0]!);

  createEffect(() => {
    const bidiClass = displayToBidiMap.get(displayName());
    if (bidiClass) {
      props.onDataChange?.(bidiClass);
    }
  });

  return <Dropdown options={names} hue={35} value={displayName()} onChange={setDisplayName} />;
}
