// src/components/advanced-search/box-types/RegexMatch.svelte
<script lang="ts">
  import Input from '../Input.svelte';
  import Dropdown from '../Dropdown.svelte';

  let regex: string = '/[A-Za-z]/u';
  let matchOn: 'Character' | 'Name' = 'Character';

  type Data = { regex: RegExp, matchOn: 'Character' | 'Name' };
	export let data: Data = { regex: getRegexFromString(regex), matchOn };
  
  $: {
    data = { regex: getRegexFromString(regex), matchOn };
  }

  function validateRegex(text: string) {
    if (getRegexFromString(text)) return true;
    return 'invalid regex';
  }

  export function getRegexFromString(text: string) {
    const res = text.match(/^\/(.+)\/([A-Za-z]*)$/);
    if (!res) return null;

    const { 1: regex, 2: flags } = res;
    try {
      return new RegExp(regex, flags);
    } catch(e) {
      return null;
    }
  }
</script>

<span>Regex</span>
<Input 
  placeholder="regular expression"
  validator={validateRegex}
  bind:value={regex} />
  
<span>Match On</span>
<Dropdown 
  options={['Character', 'Name']}
  hue={35}
  bind:value={matchOn} />

// src/components/advanced-search/box-types/RegexMatch.vue
<script setup lang="ts">
import { ref, watch } from "vue";
import Input from "../Input.vue";
import Dropdown from "../Dropdown.vue";

type Data = { regex: RegExp; matchOn: "Character" | "Name" };

interface Props {
  data?: Data;
}

defineProps<Props>();

const emit = defineEmits<{
  dataChange: [data: Data];
}>();

function getRegexFromString(text: string) {
  const res = text.match(/^\/(.+)\/([A-Za-z]*)$/);
  if (!res) return null;

  const [, regex, flags] = res;
  try {
    return new RegExp(regex!, flags);
  } catch {
    return null;
  }
}

const regex = ref("/[A-Za-z]/u");
const matchOn = ref<"Character" | "Name">("Character");

watch(
  [regex, matchOn],
  ([regexStr, match]) => {
    const regexObj = getRegexFromString(regexStr);
    if (regexObj) {
      emit("dataChange", { regex: regexObj, matchOn: match });
    }
  },
  { immediate: true },
);

function validateRegex(text: string) {
  if (getRegexFromString(text)) return true;
  return "invalid regex";
}

function handleMatchOnChange(val: string) {
  matchOn.value = val as "Character" | "Name";
}
</script>

<template>
  <div>
    <span>Regex</span>
    <Input placeholder="regular expression" :validator="validateRegex" v-model="regex" />

    <span>Match On</span>
    <Dropdown
      :options="['Character', 'Name']"
      :hue="35"
      :model-value="matchOn"
      @update:model-value="handleMatchOnChange"
    />
  </div>
</template>
