// src/components/advanced-search/box-types/UnicodeBlock.tsx
import { createSignal, createEffect, createMemo } from "solid-js";
import { Dropdown } from "../Dropdown";
import { blockLookupSig } from "$stores";

interface UnicodeBlockProps {
  data?: string;
  onDataChange?: (data: string) => void;
}

export function UnicodeBlock(props: UnicodeBlockProps) {
  const blockNames = createMemo(() => blockLookupSig().map((block) => block.name));
  const [shouldSort, setShouldSort] = createSignal(true);
  const [blockName, setBlockName] = createSignal<string>("");

  const blocks = createMemo(() => (shouldSort() ? [...blockNames()].sort() : blockNames()));

  // Initialize with first block name
  createEffect(() => {
    const names = blockNames();
    if (names.length > 0 && !blockName()) {
      setBlockName(names[0]!);
    }
  });

  createEffect(() => {
    if (blockName()) {
      props.onDataChange?.(blockName());
    }
  });

  return (
    <>
      <Dropdown options={blocks()} hue={35} value={blockName()} onChange={setBlockName} />

      <label>
        <span>Sort Blocks Alphabetically</span>
        <input
          type="checkbox"
          checked={shouldSort()}
          onChange={(e) => setShouldSort(e.currentTarget.checked)}
        />
      </label>
    </>
  );
}

// src/components/advanced-search/box-types/UnicodeBlock.vue
<script setup lang="ts">
import { ref, computed, watch } from "vue";
import Dropdown from "../Dropdown.vue";
import { blockLookup } from "$stores";

interface Props {
  data?: string;
}

defineProps<Props>();

const emit = defineEmits<{
  dataChange: [data: string];
}>();

const blockNames = computed(() => blockLookup.value.map((block) => block.name));
const shouldSort = ref(true);
const blockName = ref<string>("");

const blocks = computed(() => (shouldSort.value ? [...blockNames.value].sort() : blockNames.value));

// Initialize with first block name
watch(
  blockNames,
  (names) => {
    if (names.length > 0 && !blockName.value) {
      blockName.value = names[0]!;
    }
  },
  { immediate: true },
);

watch(
  blockName,
  (name) => {
    if (name) {
      emit("dataChange", name);
    }
  },
  { immediate: true },
);
</script>

<template>
  <div>
    <Dropdown :options="blocks" :hue="35" v-model="blockName" />

    <label>
      <span>Sort Blocks Alphabetically</span>
      <input type="checkbox" v-model="shouldSort" />
    </label>
  </div>
</template>
