// src/components/advanced-search/box-types/UnicodeBlock.vue
<script setup lang="ts">
import { ref, computed, watch } from "vue";
import Dropdown from "../Dropdown.vue";
import { blockLookup } from "$stores";

interface Props {
  data?: string;
}

defineProps<Props>();

const emit = defineEmits<{
  dataChange: [data: string];
}>();

const blockNames = computed(() => blockLookup.value.map((block) => block.name));
const shouldSort = ref(true);
const blockName = ref<string>("");

const blocks = computed(() => (shouldSort.value ? [...blockNames.value].sort() : blockNames.value));

// Initialize with first block name
watch(
  blockNames,
  (names) => {
    if (names.length > 0 && !blockName.value) {
      blockName.value = names[0]!;
    }
  },
  { immediate: true },
);

watch(
  blockName,
  (name) => {
    if (name) {
      emit("dataChange", name);
    }
  },
  { immediate: true },
);
</script>

<template>
  <div>
    <Dropdown :options="blocks" :hue="35" v-model="blockName" />

    <label>
      <span>Sort Blocks Alphabetically</span>
      <input type="checkbox" v-model="shouldSort" />
    </label>
  </div>
</template>

// src/components/advanced-search/box-types/UnicodeBlock.svelte
<script lang="ts">
	export let data: string;

	import Dropdown from '../Dropdown.svelte';
	import { blockLookupStore } from '../../../stores';

	const blockNames = $blockLookupStore.map((block) => block.name);

	let shouldSort = true;
	$: blocks = shouldSort ? [...blockNames].sort() : blockNames;

	let blockName: string = blockNames[0];

	$: {
		data = blockName;
	}
</script>

<Dropdown options={blocks} hue={35} bind:value={blockName} />

<label>
	<span>Sort Blocks Alphabetically</span>
	<input type="checkbox" bind:checked={shouldSort} />
</label>
