// src/components/advanced-search/box-types/UnicodeProperty.vue
<script setup lang="ts">
import { ref, watch } from "vue";
import Dropdown from "../Dropdown.vue";
import { properties, scripts } from "$utils/unicode";

interface Props {
  data?: string;
}

defineProps<Props>();

const emit = defineEmits<{
  dataChange: [data: string];
}>();

const activeProperty = ref(properties[0]!);
const activeScript = ref(scripts[0]!);

watch(
  [activeProperty, activeScript],
  ([property, script]) => {
    const value = property === "Script" ? `Script=${script}` : property;
    emit("dataChange", value);
  },
  { immediate: true },
);
</script>

<template>
  <div>
    <Dropdown :options="properties" :hue="35" v-model="activeProperty" />

    <Dropdown
      v-if="activeProperty === 'Script'"
      :options="scripts"
      :hue="35"
      v-model="activeScript"
    />
  </div>
</template>

// src/components/advanced-search/box-types/UnicodeProperty.svelte
<script>
	export let data;

	import Dropdown from '../Dropdown.svelte';
	import { properties, scripts } from '$utils/unicode';

	let activePropety = properties[0];
	let activeScript = scripts[0];

	$: if (activePropety === 'Script') {
		data = `Script=${activeScript}`;
	} else {
		data = activePropety;
	}
</script>

<Dropdown options={properties} hue={35} bind:value={activePropety} />

{#if activePropety === 'Script'}
	<Dropdown options={scripts} hue={35} bind:value={activeScript} />
{/if}
