// src/components/advanced-search/AdvancedSearch.svelte
<script lang="ts">
	import BoxSet from './BoxSet.svelte';
	import Button from './Button.svelte';
	import { boxesStore, getNewBox } from '$stores';
	import { createEventDispatcher, onMount } from 'svelte';

	const dispatch = createEventDispatcher();

	const onClose = (index: number) => () => {
		$boxesStore = [
			...$boxesStore.slice(0, index),
			...$boxesStore.slice(index + 1)
		];
	};

	onMount(() => {
		// If the user has previously deleted all boxSets, restore the default upon mounting again.
		if ($boxesStore.length === 0) {
			$boxesStore = [getNewBox()];
		}
	});
</script>

<form on:submit|preventDefault>
	{#each $boxesStore as box, i}
		<BoxSet bind:box on:close={onClose(i)} />
	{/each}
</form>

<div class="buttons">
	<Button on:click={() => ($boxesStore = [...$boxesStore, getNewBox()])}
		>Add Rule</Button
	>
	{#if false}
		<!-- TODO: Add setting for toggle -->
		<Button on:click={() => dispatch('search')} hue={200}>Search</Button>
	{/if}
</div>

<style>
	.buttons {
		display: flex;
		justify-content: flex-end;
	}
	.buttons :global(*) {
		margin: 5px;
	}
</style>

// src/components/advanced-search/AdvancedSearch.tsx
import { onMount, For } from "solid-js";
import { css } from "solid-styled";
import { BoxSet } from "./BoxSet";
import { Button } from "./Button";
import { boxesSig, setBoxesSig, getNewBox, type Box } from "$stores";

interface AdvancedSearchProps {
  onSearch?: () => void;
}

export function AdvancedSearch(_props: AdvancedSearchProps) {
  const onClose = (index: number) => () => {
    setBoxesSig((boxes: Box[]) => [...boxes.slice(0, index), ...boxes.slice(index + 1)]);
  };

  const updateBox = (index: number) => (box: Box) => {
    setBoxesSig((boxes: Box[]) => [...boxes.slice(0, index), box, ...boxes.slice(index + 1)]);
  };

  onMount(() => {
    if (boxesSig().length === 0) {
      setBoxesSig([getNewBox()]);
    }
  });

  css`
    .buttons {
      display: flex;
      justify-content: flex-end;
    }
    .buttons :global(*) {
      margin: 5px;
    }
  `;

  return (
    <>
      <form onSubmit={(e) => e.preventDefault()}>
        <For each={boxesSig()}>
          {(box, i) => <BoxSet box={box} onBoxChange={updateBox(i())} onClose={onClose(i())} />}
        </For>
      </form>

      <div class="buttons">
        <Button onClick={() => setBoxesSig((boxes: Box[]) => [...boxes, getNewBox()])}>
          Add Rule
        </Button>
      </div>
    </>
  );
}
