// src/components/advanced-search/AdvancedSearch.vue
<script setup lang="ts">
import { onMounted } from "vue";
import BoxSet from "./BoxSet.vue";
import Button from "./Button.vue";
import { boxes, getNewBox, type Box } from "$stores";

interface Props {
  onSearch?: () => void;
}

defineProps<Props>();

const onClose = (index: number) => () => {
  boxes.value = [...boxes.value.slice(0, index), ...boxes.value.slice(index + 1)];
};

const updateBox = (index: number) => (box: Box) => {
  boxes.value = [...boxes.value.slice(0, index), box, ...boxes.value.slice(index + 1)];
};

onMounted(() => {
  if (boxes.value.length === 0) {
    boxes.value = [getNewBox()];
  }
});

function addRule() {
  boxes.value = [...boxes.value, getNewBox()];
}
</script>

<template>
  <div>
    <form @submit.prevent>
      <BoxSet
        v-for="(box, i) in boxes"
        :key="i"
        :box="box"
        @box-change="updateBox(i)"
        @close="onClose(i)"
      />
    </form>

    <div class="buttons">
      <Button @click="addRule">Add Rule</Button>
    </div>
  </div>
</template>

<style scoped>
.buttons {
  display: flex;
  justify-content: flex-end;
}
.buttons :deep(*) {
  margin: 5px;
}
</style>

// src/components/advanced-search/AdvancedSearch.tsx
import { onMount, For } from "solid-js";
import { css } from "solid-styled";
import { BoxSet } from "./BoxSet";
import { Button } from "./Button";
import { boxesSig, setBoxesSig, getNewBox, type Box } from "$stores";

interface AdvancedSearchProps {
  onSearch?: () => void;
}

export function AdvancedSearch(_props: AdvancedSearchProps) {
  const onClose = (index: number) => () => {
    setBoxesSig((boxes: Box[]) => [...boxes.slice(0, index), ...boxes.slice(index + 1)]);
  };

  const updateBox = (index: number) => (box: Box) => {
    setBoxesSig((boxes: Box[]) => [...boxes.slice(0, index), box, ...boxes.slice(index + 1)]);
  };

  onMount(() => {
    if (boxesSig().length === 0) {
      setBoxesSig([getNewBox()]);
    }
  });

  css`
    .buttons {
      display: flex;
      justify-content: flex-end;
    }
    .buttons :global(*) {
      margin: 5px;
    }
  `;

  return (
    <>
      <form onSubmit={(e) => e.preventDefault()}>
        <For each={boxesSig()}>
          {(box, i) => <BoxSet box={box} onBoxChange={updateBox(i())} onClose={onClose(i())} />}
        </For>
      </form>

      <div class="buttons">
        <Button onClick={() => setBoxesSig((boxes: Box[]) => [...boxes, getNewBox()])}>
          Add Rule
        </Button>
      </div>
    </>
  );
}
