// src/components/table-container/ResultsContainer.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted } from "vue";
import ResultsRow from "./ResultsRow.vue";
import { activeIndex, results } from "$stores";

const resultsNum = ref(50);
const intersectionObserver = ref<HTMLDivElement | null>(null);
let intObserver: IntersectionObserver | null = null;

// Reset resultsNum when results change
watch(results, () => {
  resultsNum.value = 50;
});

onMounted(() => {
  if (!intersectionObserver.value) return;

  intObserver = new IntersectionObserver(
    (entries) => {
      const entry = entries[0];
      if (!entry?.isIntersecting) return;

      if (results.value.length > resultsNum.value) {
        resultsNum.value += 50;
      }
    },
    {
      rootMargin: "0px",
      threshold: 0.8,
    },
  );

  intObserver.observe(intersectionObserver.value);
});

onUnmounted(() => {
  intObserver?.disconnect();
});

const shownResults = computed(() => results.value.slice(0, resultsNum.value));

function handleFocus(e: FocusEvent) {
  const target = e.target as Element;
  const index = target.querySelector("img")?.dataset.index;
  if (!index) return;
  activeIndex.value = Number(index);
}

function handleKeydown(e: KeyboardEvent) {
  if (e.key === "ArrowDown" && activeIndex.value < results.value.length - 1) {
    activeIndex.value++;
  } else if (e.key === "ArrowUp" && activeIndex.value >= 0) {
    activeIndex.value--;
  }
}
</script>

<template>
  <div>
    <p>{{ results.length }} result{{ results.length > 1 ? "s" : "" }}</p>

    <div class="table" role="table" @focusin="handleFocus" @keydown="handleKeydown">
      <ResultsRow
        v-for="([codepoint, info], i) in shownResults"
        :key="codepoint"
        :index="i"
        :codepoint="codepoint"
        :info="info"
      />

      <div class="intersection-observer" ref="intersectionObserver" />
    </div>
  </div>
</template>

<style scoped>
.table {
  text-align: left;
}
p {
  text-align: left;
  margin: 0;
  opacity: 0.7;
  font-size: 0.8rem;
}
.intersection-observer {
  height: 5rem;
}
</style>

// src/components/table-container/ResultsContainer.svelte
<script lang="ts">
  import ResultsRow from './ResultsRow.svelte';
  import { lastIntersect } from '../../actions/lastIntersect';
  import { activeIndex, copiedCodepoint, resultsStore } from '$stores';

  const getInfoIcon = (el: EventTarget) => {
    if (!(el instanceof HTMLElement)) return null;
    for (const element of [el, el.parentElement]) {
      if (element instanceof HTMLImageElement && element.alt === 'info') return element;
      if (element?.classList.contains('info-icon'))return element;
    }
    return null;
  };

  function handleFocus(e: FocusEvent) {
    const index = (e.target as Element).querySelector('img')?.dataset.index;
    if (!index) return;
    $activeIndex = Number(index);
  }
  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'ArrowDown' && $activeIndex < $resultsStore.length - 1) {
      $activeIndex++;
    } else if  (e.key === 'ArrowUp' && $activeIndex >= 0) {
      $activeIndex--;
    }
  }

  let copyTextTimeoutId: ReturnType<typeof setTimeout>;
  function handleRightClick(e: MouseEvent) {
    const el = getInfoIcon(e.target as EventTarget);
    if (!el) return;

    const index = Number(el.dataset.index);
    const [codepoint] = $resultsStore[index];
    const char = String.fromCodePoint(codepoint);
    navigator.clipboard.writeText(char);

    clearTimeout(copyTextTimeoutId);
    $copiedCodepoint = codepoint;
    copyTextTimeoutId = setTimeout(() => {
      $copiedCodepoint = -1;
    }, 1000);

    e.preventDefault();
  }

  let resultsNum = 50;
  $: shownResults = $resultsStore.slice(0, resultsNum);
  resultsStore.subscribe(() => {
    resultsNum = 50;
  });
</script>

<p>
  {$resultsStore.length} result{$resultsStore.length > 1 ? 's' : ''}
</p>

<!-- svelte-ignore a11y-click-events-have-key-events -->
<!-- svelte-ignore a11y-no-static-element-interactions -->
<div class="table"
  on:contextmenu={handleRightClick} 
  use:lastIntersect 
  on:intersect={() => resultsNum += 50}
  on:focusin={handleFocus}
  on:keydown={handleKeydown}
>
  <div class="table-head row">
    <div>Character</div>
    <div>Codepoint</div>
    <div>Description</div>
  </div>

  {#each shownResults as [codepoint, info], i}
    <ResultsRow index={i} {codepoint} {info} />
  {/each}
</div>

<style>
  .table {
    text-align: left;
  }
  .table :global(.row) {
    display: grid;
    grid-template-columns: 80px 80px 1fr 50px;
    grid-gap: 10px;
    padding: 10px
  }
  .table-head {
    font-weight: bold;
    font-size: .8em;
    color: var(--label-col);
    padding: 10px 0;
  }
  p {
    text-align: left;
    margin: 0;
    opacity: .7;
    font-size: .8rem;
  }
</style>
