// src/components/table-container/info-tables/CaseMapping.vue
<script setup lang="ts">
import { computed } from "vue";
import type { UnicodeMapData } from "@emnudge/unicode-query";

interface Props {
  titlecaseMapping: UnicodeMapData["titlecaseMapping"];
  uppercaseMapping: UnicodeMapData["uppercaseMapping"];
  lowercaseMapping: UnicodeMapData["lowercaseMapping"];
}

const props = defineProps<Props>();

const caseMappings = computed(
  () =>
    Object.entries({
      titlecaseMapping: props.titlecaseMapping,
      uppercaseMapping: props.uppercaseMapping,
      lowercaseMapping: props.lowercaseMapping,
    }).filter(([, v]) => v) as [string, number][],
);
</script>

<template>
  <template v-if="caseMappings.length">
    <br />
    <table>
      <thead>
        <tr>
          <th class="title" colspan="2">Case Mapping</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="[key, value] in caseMappings" :key="key">
          <td>{{ key }}</td>
          <td>{{ String.fromCodePoint(value) }}</td>
        </tr>
      </tbody>
    </table>
  </template>
</template>

// src/components/table-container/info-tables/CaseMapping.svelte
<script lang="ts">
	import type { UnicodeMapData } from '@emnudge/unicode-query';

	const {
		titlecaseMapping,
		uppercaseMapping,
		lowercaseMapping
	}: {
		titlecaseMapping: UnicodeMapData['titlecaseMapping'];
		uppercaseMapping: UnicodeMapData['uppercaseMapping'];
		lowercaseMapping: UnicodeMapData['lowercaseMapping'];
	} = $props();

	const caseMappings = $derived(
		Object.entries({
			titlecaseMapping,
			uppercaseMapping,
			lowercaseMapping
		}).filter(([_k, v]) => v) as [string, number][]
	);
</script>

{#if caseMappings.length}
	<br />
	<table>
		<thead>
			<tr>
				<th class="title" colspan="2">Case Mapping</th>
			</tr>
		</thead>
		<tbody>
			{#each caseMappings as [key, value]}
				<tr>
					<td>{key}</td>
					<td>{String.fromCodePoint(value)}</td>
				</tr>
			{/each}
		</tbody>
	</table>
{/if}
