// src/App.vue
<script setup lang="ts">
import { onMounted } from "vue";
import { hasFirstLoaded, selectedCodepoint, searchMode, results } from "$stores";

import GitHubIcon from "$icons/GitHubIcon.vue";
import ResultsContainer from "$components/table-container/ResultsContainer.vue";
import EasySearch from "$components/EasySearch.vue";
import Header from "$components/Header.vue";
import AdvancedSearch from "$components/advanced-search/AdvancedSearch.vue";
import Loader from "$components/Loader.vue";
import InfoContainer from "$components/table-container/InfoContainer.vue";

onMounted(() => {
  import("./queryProxy");
});
</script>

<template>
  <div :class="['content', selectedCodepoint && 'middle']">
    <aside v-if="selectedCodepoint">
      <div>
        <InfoContainer
          :codepoint="selectedCodepoint.codepoint"
          :info="selectedCodepoint"
          :name="selectedCodepoint.label"
        />
      </div>
    </aside>
    <div>
      <Header />
      <GitHubIcon href="https://github.com/EmNudge/unicode-lookup" />

      <main>
        <div class="searchbox">
          <EasySearch v-if="searchMode === 'simple'" />
          <AdvancedSearch v-else />
        </div>

        <br />

        <template v-if="hasFirstLoaded">
          <ResultsContainer v-if="results.length" />
          <template v-else>
            <br />
            <p>No results fit that query :/</p>
          </template>
        </template>
        <Loader v-else />
      </main>
    </div>
    <aside v-if="selectedCodepoint" />
  </div>
</template>

<style>
body {
  overflow-y: scroll;
}
</style>

<style scoped>
main {
  text-align: center;
  margin: 0 auto;
  width: 600px;
  max-width: 100%;
}
@media (min-width: 640px) {
  main {
    max-width: none;
  }
}
.content.middle {
  display: grid;
  grid-template-columns: minmax(500px, auto) 600px 500px;
  justify-content: center;
}
@media (max-width: 1600px) {
  .content.middle {
    display: grid;
    grid-template-columns: minmax(500px, auto) 600px;
  }
}
aside div {
  position: fixed;
  width: 400px;
  overflow-y: auto;
  height: 100vh;
}
</style>

// src/App.svelte
<script lang="ts">
	import { resultsStore, currentQueryStore, easySearchStore, boxSetsStore } from './stores';
	import ResultsContainer from './components/table-container/ResultsContainer.svelte';
	import { getBoxSetsFromText } from './utils/query'
	import EasySearch from './components/EasySearch.svelte';
	import Header from './components/Header.svelte';
	import GithubIcon from './icons/github.svelte';
	import AdvancedSearch from './components/advanced-search/AdvancedSearch.svelte';

	import type { BoxSet } from './stores';
	let queryArr: BoxSet[] = [];
	$: {
		currentQueryStore.set(queryArr);
	}

	const easySearch = () =>
		queryArr = getBoxSetsFromText($easySearchStore);
	const advancedSearch = () => 
		queryArr = $boxSetsStore;

	import { searchMode, SearchMode } from './stores'
</script>

<Header />
<GithubIcon href="https://github.com/EmNudge/unicode-lookup" />

<main>
	<div class="searchbox">
		{#if $searchMode === SearchMode.SimpleSearch}
			<EasySearch on:search={easySearch} />
		{:else}
			<AdvancedSearch on:search={advancedSearch} />
		{/if}
	</div>

	<br>

	{#if $resultsStore.length}
		<ResultsContainer />
	{:else}
		<br>
		<p>No results fit that query :/</p>
	{/if}
</main>

<style>
	main {
		text-align: center;
		margin: 0 auto;
		
    width: 600px;
    max-width: 100%;
	}

	@media (min-width: 640px) {
		main {
			max-width: none;
		}
	}
</style>
